apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-app
  name: task-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-app
  template:
    metadata:
      labels:
        app: task-app
    spec:
      containers:
      - image: 259802786408.dkr.ecr.us-east-1.amazonaws.com/task-app
        name: task-app
        ports:
        - containerPort: 3000

