region          = "us-east-1"
vpc_cidr        = "10.0.0.0/16"
cluster-name    = "EKS-cluster-test"
security_group  = "terraform-eks-demo-cluster"
route_53_zone   = "its-testtask-node.fun"
node_group_name = "demo"